name: open_heimdall
description: A error notification API
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  coruja: ^0.0.0
  postgres: ^2.3.0
  googleapis_auth: ^1.1.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
